### ISSUE TITLE
Port `test_min_dot_size` to XPU

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2980]
UT added in https://github.com/intel/intel-xpu-backend-for-triton/pull/2978 from upstream commit https://github.com/triton-lang/triton/commit/5700c1468773d224075597f53710a79a796d5fd2.

**Comment by etiotto** [comment]
I get this error: 
```
FAILED test_compile_errors.py::test_min_dot_size[dtype0] - TypeError: ASTSource.__init__() got an unexpected keyword argument 'constexprs'
```

This happens because our version of `ASTSource` is not up to date. We need `https://github.com/triton-lang/triton/pull/5220` first.

**Comment by etiotto** [comment]
@whitneywhtsang I see from the log that you have merged but then reverted the PR with the changes we need:
```
commit 492ea92c05ac2fdde8abf7ded241442f029217ea
Author: Whitney Tsang <whitney.tsang@intel.com>
Date:   Tue Dec 10 04:02:08 2024 +0000

    Revert "[FRONTEND] added support for tuples (#5220)"
    
    This reverts commit 9743ec0dca5bbd9dbce20adc3ee273af6b095f94.
```
What was the reason for reverting that commit ?

**Comment by whitneywhtsang** [comment]
> What was the reason for reverting that commit ?

Because it causes UTs failures.

**Comment by whitneywhtsang** [comment]
Depends on https://github.com/intel/intel-xpu-backend-for-triton/issues/2979.
