### ISSUE TITLE
[vLLM] Fix `vllm_xpu_kernels` PyTorch regressions

### ISSUE THREAD

**Issue by quinnlp** [intel/intel-xpu-backend-for-triton#6934]
A recent PyTorch pin update(https://github.com/intel/intel-xpu-backend-for-triton/commit/c7d0daaf3d70be12be0450085f000552c2efa0b0) caused many vLLM test regressions as well as a `batched moe fp8` benchmark regression (https://github.com/intel/intel-xpu-backend-for-triton/issues/6889).

Example error:
```
AttributeError: '_OpNamespace' '_C' object has no attribute 'get_xpu_view_from_cpu_tensor'
```

The problem is that the `vllm_xpu kernels` wheel requires a different PyTorch version than the new pin.

The benchmark regression was fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/6891 by implementing missing ops in PyTorch. Incorporating this fix for the tests is not sustainable.

Instead, we can build the `vllm_xpu_kernels` from source to control the PyTorch version and keep it consistent with our pin.

https://github.com/intel/intel-xpu-backend-for-triton/pull/6926 implements the change and reverts the benchmark fix (https://github.com/intel/intel-xpu-backend-for-triton/commit/5960d376d8609d3fe3b2764ca65cbde27080d909).

**Comment by quinnlp** [comment]
I noticed that building `vllm_xpu_kernels` from source takes a **VERY** long time:
* `vllm` source + `vllm_xpu_kernels` wheel: 1 minute (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25843234737)
* `vllm` source + `vllm_xpu_kernels` source: 2 hours (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25836938143)

Building an older commit of `vllm_xpu_kernels` from source is **MUCH** faster:
* `vllm` source + old `vllm_xpu_kernels` source: 4 minutes (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25868012504)


We do not know why building `vllm_xpu_kernels` has become so slow.

We can cache the build (like we do with PyTorch) to help. But, clean builds will still be very slow.
