### PR TITLE
[vLLM] Build vLLM XPU kernels from source and upload/download via nightly wheels

### LINKED ISSUE #6934: [vLLM] Fix `vllm_xpu_kernels` PyTorch regressions
A recent PyTorch pin update(https://github.com/intel/intel-xpu-backend-for-triton/commit/c7d0daaf3d70be12be0450085f000552c2efa0b0) caused many vLLM test regressions as well as a `batched moe fp8` benchmark regression (https://github.com/intel/intel-xpu-backend-for-triton/issues/6889).

Example error:
```
AttributeError: '_OpNamespace' '_C' object has no attribute 'get_xpu_view_from_cpu_tensor'
```

The problem is that the `vllm_xpu kernels` wheel requires a different PyTorch version than the new pin.

The benchmark regression was fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/6891 by implementing missing ops in PyTorch. Incorporating this fix for the tests is not sustainable.

Instead, we can build the `vllm_xpu_kernels` from source to control the PyTorch version and keep it consistent with our pin.

https://github.com/intel/intel-xpu-backend-for-triton/pull/6926 implements the change and reverts the benchmark fix (https://github.com/intel/intel-xpu-backend-for-triton/commit/5960d376d8609d3fe3b2764ca65cbde27080d909).

### PR DESCRIPTION
**Pull request by quinnlp**
Closes https://github.com/intel/intel-xpu-backend-for-triton/issues/6934.

This patch changes our vLLM install script to build and install the vllm-xpu-kernels module from source instead of from a wheel. This ensures that the vllm-xpu-kernels is compatible with the version of torch that we install. We have encountered issues where a vllm-xpu-kernels wheel relies on an older version of torch than the commit that is pinned in the repo. This patch also adds a vllm-xpu-kernels pin for consistency across builds/runs.

This patch implements nightly wheel upload/download for vllm-xpu-kernels. This is to reduce the long build times for vllm-xpu-kernels source builds. The vllm project cannot be be added to the nightly wheels because we need an editable install so we can apply tensor descriptor patches to the benchmarks in our benchmarking script. Source builds of the vllm project are fast anyways so this is not a problem. This patch also modifies and refactors the install-vllm.sh script to match the functionality in the install-pytorch.sh script.

Since vLLM depends on torch, I've decided to add the vLLM XPU kernels wheel build to the `nightly-wheels.yml` workflow. This adds about 1 hour to the nightly wheel builds.

---
vLLM benchmarks: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26805144286
vLLM benchmarks BMG: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26805153145
vLLM tests: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26805191632 (failed count: 223 -> 32).
vLLM tests BMG: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26805209094 (failed count: 223 -> 5)

The patch has no impact on vLLM benchmark performance. Most of the tests failing on main are now passing, the remaining failures need to be investigated.

### CODE REVIEW

**Comment by quinnlp** [comment]
[Triton benchmarks, PVC / benchmarks / Triton benchmarks](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26522046734/job/78139875393?pr=6926) failures are unrelated and also on main: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26510170145

**Comment by quinnlp** [comment]
batched_moe fp8 benchmark is failing on BMG only: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26519625499.

It seems that a vllm-xpu-kernels op is not being built for BMG? Looking into it today. A workaround is to not remove this part of Whitney's patch (https://github.com/intel/intel-xpu-backend-for-triton/commit/5960d376d8609d3fe3b2764ca65cbde27080d909):
```diff
-            torch.ops._C.dynamic_scaled_fp8_quant(output, input, scale)
+            if hasattr(torch.ops._C, 'dynamic_scaled_fp8_quant'):
+                torch.ops._C.dynamic_scaled_fp8_quant(output, input, scale)
+            else:
+                fp8_max = torch.finfo(out_dtype).max
+                amax = input.abs().max().clamp(min=1e-12)
+                scale[0] = amax / fp8_max
+                output.copy_((input / scale).clamp(-fp8_max, fp8_max).to(out_dtype))
```

**Comment by whitneywhtsang** [comment]
We can do two steps, as long as we fix it timely, I assume vLLM tests on BMG would fail too.

**Comment by quinnlp** [comment]
I rebased to pick up the Triton benchmarks fix: https://github.com/intel/intel-xpu-backend-for-triton/commit/9cd10e10349a17fe33dddd4715a60cb22547f46a.

> batched_moe fp8 benchmark is failing on BMG only: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26519625499.
> 
> It seems that a vllm-xpu-kernels op is not being built for BMG? Looking into it today. A workaround is to not remove this part of Whitney's patch ([5960d37](https://github.com/intel/intel-xpu-backend-for-triton/commit/5960d376d8609d3fe3b2764ca65cbde27080d909)):
> 
> ```diff
> -            torch.ops._C.dynamic_scaled_fp8_quant(output, input, scale)
> +            if hasattr(torch.ops._C, 'dynamic_scaled_fp8_quant'):
> +                torch.ops._C.dynamic_scaled_fp8_quant(output, input, scale)
> +            else:
> +                fp8_max = torch.finfo(out_dtype).max
> +                amax = input.abs().max().clamp(min=1e-12)
> +                scale[0] = amax / fp8_max
> +                output.copy_((input / scale).clamp(-fp8_max, fp8_max).to(out_dtype))
> ```

I was not able to reproduce the batched_moe benchmark and moe test failures locally on a bmg machine. I have some runs queued to see if the issues are still reproducible in CI after rebasing against main and building a new wheel:
* vLLM benchmarks BMG: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26589297892/job/78343555848
* vLLM tests: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/26589274492/job/78343490772

**Comment by quinnlp** [comment]
I've reapplied https://github.com/intel/intel-xpu-backend-for-triton/commit/5960d376d8609d3fe3b2764ca65cbde27080d909 and rerun the vLLM benchmarks and tests. There are no regressions now. We CAN squash merge this PR now.

**Review by whitneywhtsang — APPROVED** [review]

**Review by dev-tomek — APPROVED** [review]
