### ISSUE TITLE
Fix `test_auto_grf_on_build_failure` failure on LTS

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#6136]
The test case is introduced in https://github.com/intel/intel-xpu-backend-for-triton/pull/6123.
CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/22154913102/job/64057526805

**Comment by whitneywhtsang** [comment]
FYI also fails on CRI.

**Comment by Egor-Krivov** [comment]
Looks like it is a known issue that zeinfo is missing spill size in LTS driver
https://github.com/intel/intel-xpu-backend-for-triton/issues/5717#issuecomment-3835355337

**Comment by Egor-Krivov** [comment]
@whitneywhtsang So, regarding CRI: I'll just add a xfail skip like in the first test of `test_driver.py` file.

Regarding LTS: the error is not from my PR, looks like the root issue already appeared here: https://github.com/intel/intel-xpu-backend-for-triton/issues/5717#issuecomment-3835355337 
When compilation failed due to too many registers used, it will not report correct return code, but zeinfo file will miss register count. This issue is fixed in rolling, but not in LTS. I suggest to just add my new test to skip list file on LTS specifically [here](https://github.com/intel-tools/intel-xpu-backend-for-triton/blob/main-interim/scripts/skiplist/lts/intel.txt).

Additionally, we could create an issue to solve the missing zeinfo file in some conditions in LTS driver, but it looks like it is already fixed in the rolling driver, so the only goal would be to find our local triton workaround for LTS driver.

@whitneywhtsang Are you fine with my suggested fix? Do you think we need a new issue specifically for LTS driver?

**Comment by whitneywhtsang** [comment]
xfail on CRI and skip on LTS LGTM. 
We have already suggested driver team to backport the zeinfo fix to LTS driver.
Don't think we need to make additional changes in Triton for LTS.
