### ISSUE TITLE
Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#5394]
### Describe the bug

Hi, team:
We found Inductor UT failure in test_native_matmul.py which use tl.do to build a GEMM kernel instead of template. But got error:  ZE_RESULT_ERROR_INVALID_KERNEL_NAME

Following is the triton kernel and reproducer

[native_mm.py](https://github.com/user-attachments/files/23177918/native_mm.py)

### Environment details

PyTorch: 39a70cead11e817ef97579674c3652ea343fcaf4 （ main branch)

GPU: PVC

OS: Linux

**Comment by HBN-MichalSzy** [comment]
This test is doing `triton_heuristics.reduction`  on a quite straight forward triton kernel with dot product. Based on triton_heuristics.reduction inputs, there are 19 different configs generated to compile same Triton kernel. Out of those 19, 2 are  failing due to incorrect num_warps specified. When I change num_warps to 8 on problematic configs, the test is passing.

```
XBLOCK: 32, YBLOCK: 32, R0_BLOCK: 16, num_warps: 2, num_ctas: 1, num_stages: 1, maxnreg: None  -  SUCCESSFUL
XBLOCK: 32, YBLOCK: 32, R0_BLOCK: 128, num_warps: 4, num_ctas: 1, num_stages: 2, maxnreg: None  -  SUCCESSFUL
XBLOCK: 32, YBLOCK: 64, R0_BLOCK: 32, num_warps: 8, num_ctas: 1, num_stages: 5, maxnreg: None  -  SUCCESSFUL
XBLOCK: 64, YBLOCK: 32, R0_BLOCK: 32, num_warps: 8, num_ctas: 1, num_stages: 5, maxnreg: None  -  SUCCESSFUL
...
XBLOCK: 64, YBLOCK: 128, R0_BLOCK: 128, num_warps: 4, num_ctas: 1, num_stages: 4, maxnreg: None  -  FAILED (**SUCCESSFUL with num_warps=8**)
XBLOCK: 128, YBLOCK: 128, R0_BLOCK: 64, num_warps: 4, num_ctas: 1, num_stages: 3, maxnreg: None  -  FAILED (**SUCCESSFUL with num_warps=8**)
```

The config generation was added recently in https://github.com/pytorch/pytorch/pull/157743 and the simple fix can be done on PT side in two places:

- https://github.com/pytorch/pytorch/blob/main/torch/_inductor/runtime/triton_heuristics.py#L2745
- https://github.com/pytorch/pytorch/blob/main/torch/_inductor/runtime/triton_heuristics.py#L2750

However, this is generic Triton code, not related to just XPU, so it's better to add extra handling afterwards XPU-specific that updates those configs. @etiotto , @whitneywhtsang any thoughts on this? Is there any guideline already how to fix such kind of issue perhaps? Otherwise, I will propose something on PT side.

**Comment by etiotto** [comment]
Looks like a know limitation. Triton produces LLVM IR and eventually passes it to IGC for compilation. IGC might not be able to schedule the kernel, due to excessive number of register spills. When that is the case IGC produces an SPV module that doesn't contain any kernel in it. Triton loads the module, then uses L0 to query whether the module contains the kernel function. If L0 doesn;t find the kernel, Triton then should report a message stating that the kernel is not present in the module:

```
Module doesn't contain any kernels. Please attempt to tune the 'num_warps' parameter.
Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```

The message suggest to tune `num_warps`. So I think that is what's happening here.

@etaf shouldn't inductor autotune the kernel and discard configurations that do not compile or are slower than other configurations ?

**Comment by etaf** [comment]
> Looks like a know limitation. Triton produces LLVM IR and eventually passes it to IGC for compilation. IGC might not be able to schedule the kernel, due to excessive number of register spills. When that is the case IGC produces an SPV module that doesn't contain any kernel in it. Triton loads the module, then uses L0 to query whether the module contains the kernel function. If L0 doesn;t find the kernel, Triton then should report a message stating that the kernel is not present in the module:
> 
> ```
> Module doesn't contain any kernels. Please attempt to tune the 'num_warps' parameter.
> Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
> ```
> 
> The message suggest to tune `num_warps`. So I think that is what's happening here.
> 
> [@etaf](https://github.com/etaf) shouldn't inductor autotune the kernel and discard configurations that do not compile or are slower than other configurations ?

Thanks @etiotto , cuda can pass this case, I'll check the difference in Inductor side.

**Comment by vlad-penkin** [comment]
@etaf it's a known limitation, can we close this ticket?

**Comment by etaf** [comment]
> [@etaf](https://github.com/etaf) it's a known limitation, can we close this ticket?

Sorry, I'll need to verify a few days later.

**Comment by etiotto** [comment]
@etaf any update?

**Comment by etaf** [comment]
Hi @HBN-MichalSzy @etiotto,
sorry — I was occupied with another urgent task earlier and didn’t read your analysis carefully. Yes, I can fix this on the Inductor side. Besides, could you share the limitations of the following two configs?
```
XBLOCK: 64, YBLOCK: 128, R0_BLOCK: 128, num_warps: 4, num_ctas: 1, num_stages: 4, maxnreg: None  -  FAILED (**SUCCESSFUL with num_warps=8**)
XBLOCK: 128, YBLOCK: 128, R0_BLOCK: 64, num_warps: 4, num_ctas: 1, num_stages: 3, maxnreg: None  -  FAILED (**SUCCESSFUL with num_warps=8**)
```

**Comment by etaf** [comment]
Fix PR: https://github.com/pytorch/pytorch/pull/169167

**Comment by etaf** [comment]
Hi, @etiotto @HBN-MichalSzy, I reopened this issue because:

The exception raised by Triton is a C++ PyExc_RuntimeError, and on the Inductor side I currently have to catch it using a generic RuntimeError, which may also capture unrelated Inductor-level runtime errors. To avoid this ambiguity, I hope the Triton team can catch the PyExc_RuntimeError at the Python level and re-throw a more specific exception to Inductor—similar to how CUDA raises PTXASError.

Since we will also enable the zebin format in Inductor, please also raise the corresponding specific exception as well when generating zebin binaries.

**Comment by HBN-MichalSzy** [comment]
I will work on better error handling here in a week after next week (I'm ooo).

**Comment by HBN-MichalSzy** [comment]
I have added IntelGPUError for our specific use cases. Modified generic part of Triton so it can be upstreamed. @etiotto please review  #5628 and if fine, I create PR to upstream as well.

**Comment by HBN-MichalSzy** [comment]
@etaf change in intel-xpu-backend-for-triton repo has been merged. It introduced new type of exception ``IntelGPUError`` which is from the same place as other exceptions caught in your Draft PR. However, there was no approval to introduce this Error to upstream Triton repo, so you need to guard importing this symbol - for example like PT team suggested in https://github.com/triton-lang/triton/pull/8963#issuecomment-3655900844

**Comment by etaf** [comment]
Thanks for the info! I'll guard the importing in PyTorch side.

**Comment by etaf** [comment]
Hi， @HBN-MichalSzy @etiotto ， After updated triton to 3.7 release, the native_mm.py reported in this thread get compilation error, could you please repoen this issue?
```
Traceback (most recent call last):
  File "/workspace2/xinanlin/pytorch/native_mm.py", line 56, in <module>
    triton_red_fused_addmm_mm_0 = async_compile.triton('triton_red_fused_addmm_mm_0', '''
  File "/workspace2/xinanlin/pytorch/torch/_inductor/async_compile.py", line 483, in triton
    kernel.precompile(
  File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 501, in precompile
    self._precompile_worker()
  File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 523, in _precompile_worker
    compile_results.append(self._precompile_config(c))
  File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 879, in _precompile_config
    binary = triton.compile(*compile_args, **compile_kwargs)
  File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 338, in compile
    next_module = compile_ir(module, metadata)
  File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 513, in <lambda>
    stages["zebin"] = lambda src, metadata: self.make_zebin(src, metadata, options)
  File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 480, in make_zebin
    spill_size = extract_spill_size_from_zebin(fbin)
  File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 83, in extract_spill_size_from_zebin
    raise RuntimeError('Internal Triton ZEBIN codegen error:'
RuntimeError: Internal Triton ZEBIN codegen error:Section .ze_info not found in zebin
```

**Comment by montaguelhz** [comment]
I encountered the same error when compiling `_w8a8_triton_block_scaled_mm` in [vllm](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py#L1173) to support offline fp8 quantization in intel GPU. My triton version is 3.5.1.
```
(EngineCore_DP0 pid=8084) WARNING 02-02 07:13:14 [_logger.py:68] Using default W8A8 Block FP8 kernel config. Performance might be sub-optimal! Config file not found at /llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/configs/N=4096,K=1024,device_name=Intel(R)_Graphics_[0xe211],dtype=fp8_w8a8,block_shape=[128,128].json
Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
......
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/ipex_quant.py", line 411, in apply
(EngineCore_DP0 pid=8084)     return self.w8a8_block_fp8_linear.apply(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 257, in apply
(EngineCore_DP0 pid=8084)     output = self.w8a8_blockscale_op(
(EngineCore_DP0 pid=8084)              ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 366, in _run_triton
(EngineCore_DP0 pid=8084)     return torch.ops.vllm.w8a8_triton_block_scaled_mm_func(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1255, in __call__
(EngineCore_DP0 pid=8084)     return self._op(*args, **kwargs)
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 80, in _w8a8_triton_block_scaled_mm_func
(EngineCore_DP0 pid=8084)     return w8a8_triton_block_scaled_mm(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 846, in w8a8_triton_block_scaled_mm
(EngineCore_DP0 pid=8084)     _w8a8_triton_block_scaled_mm[grid](
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 393, in <lambda>
(EngineCore_DP0 pid=8084)     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
(EngineCore_DP0 pid=8084)                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 623, in run
(EngineCore_DP0 pid=8084)     kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
(EngineCore_DP0 pid=8084)     ^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/compiler/compiler.py", line 474, in __getattribute__
(EngineCore_DP0 pid=8084)     self._init_handles()
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/compiler/compiler.py", line 462, in _init_handles
(EngineCore_DP0 pid=8084)     self.module, self.function, self.n_regs, self.n_spills, self.n_max_threads = driver.active.utils.load_binary(
(EngineCore_DP0 pid=8084)                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/backends/intel/driver.py", line 213, in load_binary
(EngineCore_DP0 pid=8084)     return self.shared_library.load_binary(args)
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084) RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```

**Comment by anmyachev** [comment]
> Hi， [@HBN-MichalSzy](https://github.com/HBN-MichalSzy) [@etiotto](https://github.com/etiotto) ， After updated triton to 3.7 release, the native_mm.py reported in this thread get compilation error, could you please repoen this issue?
> 
> ```
> Traceback (most recent call last):
>   File "/workspace2/xinanlin/pytorch/native_mm.py", line 56, in <module>
>     triton_red_fused_addmm_mm_0 = async_compile.triton('triton_red_fused_addmm_mm_0', '''
>   File "/workspace2/xinanlin/pytorch/torch/_inductor/async_compile.py", line 483, in triton
>     kernel.precompile(
>   File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 501, in precompile
>     self._precompile_worker()
>   File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 523, in _precompile_worker
>     compile_results.append(self._precompile_config(c))
>   File "/workspace2/xinanlin/pytorch/torch/_inductor/runtime/triton_heuristics.py", line 879, in _precompile_config
>     binary = triton.compile(*compile_args, **compile_kwargs)
>   File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 338, in compile
>     next_module = compile_ir(module, metadata)
>   File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 513, in <lambda>
>     stages["zebin"] = lambda src, metadata: self.make_zebin(src, metadata, options)
>   File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 480, in make_zebin
>     spill_size = extract_spill_size_from_zebin(fbin)
>   File "/home/xinanlin/xinanlin/miniforge3/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 83, in extract_spill_size_from_zebin
>     raise RuntimeError('Internal Triton ZEBIN codegen error:'
> RuntimeError: Internal Triton ZEBIN codegen error:Section .ze_info not found in zebin
> ```

I can reproduce it.

**Comment by anmyachev** [comment]
> I encountered the same error when compiling `_w8a8_triton_block_scaled_mm` in [vllm](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py#L1173) to support offline fp8 quantization in intel GPU. My triton version is 3.5.1.

Hi @montaguelhz, do you have the opportunity to try it with Triton 3.6.0?

**Comment by anmyachev** [comment]
> Since we will also enable the zebin format in Inductor, please also raise the corresponding specific exception as well when generating zebin binaries.

This part is missing.

**Comment by anmyachev** [comment]
@etaf first of all, please change exception type from `RuntimeError` to `IntelGPUError` in https://github.com/pytorch/pytorch/pull/169167 and add this new exception here: https://github.com/pytorch/pytorch/blob/bbc2f7674eeb868439e513e0fec87a8edbdd4830/torch/_inductor/runtime/triton_heuristics.py#L523

This change is required on Triton side: https://github.com/intel/intel-xpu-backend-for-triton/pull/6028. Could you try it before we merge it?

**Comment by montaguelhz** [comment]
> > I encountered the same error when compiling `_w8a8_triton_block_scaled_mm` in [vllm](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py#L1173) to support offline fp8 quantization in intel GPU. My triton version is 3.5.1.
> 
> Hi [@montaguelhz](https://github.com/montaguelhz), do you have the opportunity to try it with Triton 3.6.0?

Cool, I'm happy to try. Also, I was able to compile the code after changing `num_warps` to 8 and I'd like to know if this change will affect performance.

**Comment by etaf** [comment]
> [@etaf](https://github.com/etaf) first of all, please change exception type from `RuntimeError` to `IntelGPUError` in [pytorch/pytorch#169167](https://github.com/pytorch/pytorch/pull/169167) and add this new exception here: https://github.com/pytorch/pytorch/blob/bbc2f7674eeb868439e513e0fec87a8edbdd4830/torch/_inductor/runtime/triton_heuristics.py#L523
> 
> This change is required on Triton side: [#6028](https://github.com/intel/intel-xpu-backend-for-triton/pull/6028). Could you try it before we merge it?

Hi, @anmyachev I've verifyed #6028 works, would you like to cherry-pick to release 3.7.x branch so that my PR can work?

**Comment by anmyachev** [comment]
> > [@etaf](https://github.com/etaf) first of all, please change exception type from `RuntimeError` to `IntelGPUError` in [pytorch/pytorch#169167](https://github.com/pytorch/pytorch/pull/169167) and add this new exception here: https://github.com/pytorch/pytorch/blob/bbc2f7674eeb868439e513e0fec87a8edbdd4830/torch/_inductor/runtime/triton_heuristics.py#L523
> > This change is required on Triton side: [#6028](https://github.com/intel/intel-xpu-backend-for-triton/pull/6028). Could you try it before we merge it?
> 
> Hi, [@anmyachev](https://github.com/anmyachev) I've verifyed [#6028](https://github.com/intel/intel-xpu-backend-for-triton/pull/6028) works, would you like to cherry-pick to release 3.7.x branch so that my PR can work?

Hi @etaf,  sure: https://github.com/intel/intel-xpu-backend-for-triton/pull/6038
