### ISSUE TITLE
[vLLM] unified attention unknown benchmarks attribute

### ISSUE THREAD

**Issue by quinnlp** [intel/intel-xpu-backend-for-triton#6855]
First bad: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25425814471
Last good: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25366865213

Affected benchmarks:
```
unified attention bf16
unified attention fp8
```

Error:
```
Traceback (most recent call last):
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/unified_attention/unified_attention_benchmark.py", line 243, in <module>
    ATTENTION_CONFIGS_BF16 = _build_attention_configs(MODELS_BF16)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/unified_attention/unified_attention_benchmark.py", line 236, in _build_attention_configs
    if is_enough_memory(x_val=x_val):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/unified_attention/unified_attention_benchmark.py", line 171, in is_enough_memory
    expected_output_mem = output_mem if benchmark_suite.BENCHMARKING_CONFIG["verify"] else 0
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'triton_kernels_benchmark' has no attribute 'BENCHMARKING_CONFIG'. Did you mean: 'BENCHMARKING_METHOD'?
```

Commit range:
```
85b80b982 [VLLM][Benchmarks] Reduce peak memory in unified_attention benchmark (#6794)
86f3329db Merge commit '4790c35390e62830fed7210d69f5988accf8aeda'
d58537766 Merge OpenAI Triton commit `ef05530` (#6832)
bffdc6496 Remove LowerTo2DBlockLoad pass from pipeline (#6850)
23013befd [TritonIntelGPU] Add Subgroup2DBlockLoadFromPtrOpConversion for ttig.2d_block_load_from_ptr (#6847)
1be91ccec Unskip `test_core.py::test_noinline[shared]` test since it's already fixed in agama 1222 (#6783)
d86009398 Skip test_shared_atomic_scatter_add on XPU (#6836)
f2598d012 Merge commit 'ef0553085258766a9457f52a87b423be2d24cbd5'
ff30831d8 Fix OSTYPE to support cygwin (#6830)
5718f2c7d Re-check #5984: Revert "Skip failed matmuls for B580 (xe2)" (#6120)
```

---

Bisected to:
```
85b80b982 [VLLM][Benchmarks] Reduce peak memory in unified_attention benchmark (#6794)
```

85b80b982 introduces this change.
