### ISSUE TITLE
[vLLM] New PyTorch pin causes no attribute regression for batched moe fp8

### ISSUE THREAD

**Issue by quinnlp** [intel/intel-xpu-backend-for-triton#6889]
First bad: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25562090911
Last good: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25545953719

Affected benchmarks:
```
batched moe fp8 triton
```

Error:
```
Traceback (most recent call last):
Running batched MM benchmark...
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/batched_moe/batched_moe_benchmark.py", line 272, in <module>
    _benchmark_mm.run(show_plots=False, print_data=True)
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.12.7/lib/python3.12/site-packages/triton_kernels_benchmark/benchmark_testing.py", line 575, in run
    df = self._run(bench, args.reports, show_plots, print_data, mark_args=args, run_counter=run_counter,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.12.7/lib/python3.12/site-packages/triton_kernels_benchmark/benchmark_testing.py", line 500, in _run
    ret = self.fn(**x_args, **{bench.line_arg: y}, **bench.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/batched_moe/batched_moe_benchmark.py", line 160, in benchmark
    A, A_q, A_scale = make_quantized_test_activations(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/vllm/batched_moe/tests/kernels/moe/utils.py", line 243, in make_quantized_test_activations
    a_q[e], a_scale_l[e] = moe_kernel_quantize_input(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/vllm/vllm/model_executor/layers/fused_moe/utils.py", line 286, in moe_kernel_quantize_input
    return _fp8_quantize(A, A_scale, per_act_token_quant, block_shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/vllm/vllm/model_executor/layers/fused_moe/utils.py", line 141, in _fp8_quantize
    A, A_scale = ops.scaled_fp8_quant(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/vllm/vllm/_custom_ops.py", line 2050, in scaled_fp8_quant
    torch.ops._C.dynamic_scaled_fp8_quant(output, input, scale)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.12.7/lib/python3.12/site-packages/torch/_ops.py", line 1385, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' '_C' object has no attribute 'dynamic_scaled_fp8_quant'
```

Commit range:
```
654a1f275 Rewrite `findDefiningOpOfType` as worklist-based `findAllMakeTensorDescOps` (#6862)
e7f4c0a2f (origin/dev/wdziurdz/merge-31) [Intel] Fix test_fpsan after merge
c7d0daaf3 Update PyTorch pin (#6833)
887cb9a22 Merge commit '7a023215a3eb48ba45219b1d4d7e8f5dd8e48023'
0ff79e20a Enable `LowerTo2DBlockLoad` pass (#6856)
```

---

Bisected to:
```
c7d0daaf3 Update PyTorch pin (#6833)
```

c7d0daaf3: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25568616903
887cb9a22: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/25568661477

c7d0daaf3d70be12be0450085f000552c2efa0b0 updated the PyTorch pin. It seems that the PyTorch inferace has changed. Maybe updating the vLLM  pin will fix this? The benchmark also fails with my current PR to update the vLLM pin to https://github.com/vllm-project/vllm/commit/8189a15914ca48461acf106f126c58ef7e41c9ee (there are ~20 commits between this commit and the top of main). After merging my PR, I will try updating the pin to the top of main

FYI @anmyachev

**Comment by anmyachev** [comment]
@quinnlp it might be a good idea to add a short test (for example, just a subset of benchmarks) to check the vLLM compatibility when updating the PyTorch pin, which would run automatically, preferably no more than 5 minutes.
