### ISSUE TITLE
`test/inductor/test_flex_attention.py::TestFlexAttentionXPU::test_seq_masking_xpu_float16` is broken

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#5308]
CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18493060126/job/52690986128

To reproduce: `python test/inductor/test_flex_attention.py TestFlexAttentionXPU.test_seq_masking_xpu_float16`

Error:
```bash
L0 build module failed. Log: 
error: undefined reference to `__internal_intel_sub_group_2d_block_read_8b_1r16x4c_cache_controls'
in function: '__internal_intel_sub_group_2d_block_read_8b_1r16x4c_cache_controls' called by kernel: 'triton_tem_fused_0'

error: backend compiler failed build.

Error during Intel loadBinary: ZE_RESULT_ERROR_MODULE_BUILD_FAILURE
```

**Comment by anmyachev** [comment]
FYI @whitneywhtsang 
```bash
e7a7c7abc1ab9ed4cb77c0f3b4670f0e311a96ac is the first bad commit
commit e7a7c7abc1ab9ed4cb77c0f3b4670f0e311a96ac
Author: Whitney Tsang <whitney.tsang@intel.com>
Date:   Sun Oct 12 23:09:26 2025 -0400

    [LoadOpToBlockIOConversion] Refactor block load codegen for regular pointer (#5242)
    
    Refactors the 2D block load lowering to simplify regular pointer load
    code generation.
    The codegen now relies on linear layout and `getBlockIOTileSize`.
    
    PVC:
    https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18207021859
    (GOOD)
    BMG:
    https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/18207010226
    (GOOD)
    
    ---------
    
    Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>

 .../tensor-pointer-load-block-2d.mlir              |  76 +--
 .../lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp | 695 +++++----------------
 2 files changed, 178 insertions(+), 593 deletions(-)
```
