### ISSUE TITLE
[FlexAttention] Failure from PyTorch pin update

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#4242]
`AttributeError: module 'triton.language.extra.cuda' has no attribute 'experimental_tensormap_fenceproxy_acquire'`

Last good: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/15043421870
First bad: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/15071816609

Failures starting from https://github.com/intel/intel-xpu-backend-for-triton/commit/767f45b877.

**Comment by anmyachev** [comment]
https://github.com/intel/intel-xpu-backend-for-triton/pull/3951/commits/053f98b79076f3e819eb637e61c3b6b1014ad8fe

**Comment by anmyachev** [comment]
PyTorch change that breaks CI: https://github.com/pytorch/pytorch/commit/3e8bda4ad57fa78b42b84d9f8a32942d34d2132c
