### PR TITLE
Update PyTorch upstream pin

### LINKED ISSUE #1840: PyTorch 2.4 on A770: Required aspect fp64 is not supported on the device
600 tests fail with PyTorch 2.4 on A770, for example:

```
FAILED language/test_standard.py::test_maximum_minium[maximum-bfloat16] - RuntimeError: Required aspect fp64 is not supported on the device
```

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10330161539/job/28598819656

### PR DESCRIPTION
**Pull request by anmyachev**
Closes #1840

CI on PyTorch main status with noop IPEX: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10422253663

For rolling there is the following error (10 tutorial):
* `AttributeError: module 'torch.xpu' has no attribute 'set_fp32_math_mode'` (should be fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/1860)

For LTS:
* `Failed to create Level Zero tracer: 2013265921` (instrumentation/test_gpuhello.py)

### CODE REVIEW

**Comment by anmyachev** [comment]
Most of the failed tests (from #1840) are fixed by this change (checked in https://github.com/intel/intel-xpu-backend-for-triton/pull/1879).
