### PR TITLE
Pin numpy<2.0 to make pytorch working

### LINKED ISSUE #1386: error: ‘PyArray_Descr’ has no member named ‘elsize’
pytorch<2.3.0 doesn't support numpy 2.0 so you may experience the issue when running `./scripts/test-triton.sh --venv --tutorial`.

### PR DESCRIPTION
**Pull request by YarShev**
Closes #1386.

### CODE REVIEW

**Review by pbchekin — APPROVED** [review]

File: .github/actions/setup-pytorch/action.yml [hunk 1]
```diff
@@ -106,13 +106,6 @@ runs:
         wget https://raw.githubusercontent.com/intel/torch-xpu-ops/main/.github/scripts/apply_torch_pr.py
         python apply_torch_pr.py --pr-list https://github.com/pytorch/pytorch/pull/124147 --pr-list https://github.com/pytorch/pytorch/pull/126516
 
-    # FIXME: Old PyTorch does not work with numpy==2.0.0
```
Comment (pbchekin) [inline .github/actions/setup-pytorch/action.yml:109]: I would recommend keeping this in the workflow, since we usually build/install PyTorch before Triton and PyTorch does not have any constraints for numpy (https://github.com/pytorch/pytorch/blob/main/requirements.txt#L5). Also the change in setup.py is only for `test` and we do not always install `triton[test]` in our workflows.

**Review by pbchekin — CHANGES_REQUESTED** [review]
See my comment about keeping the step in workflow.

File: .github/actions/setup-pytorch/action.yml (hunk 1 above)
Comment (YarShev) [reply .github/actions/setup-pytorch/action.yml]: Reverted the change

**Review by pbchekin — APPROVED** [review]
