### ISSUE TITLE
PyTorch build is broken on LTS2 machine

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#7449]
Error ([link](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/29321647530/job/87048200282?pr=7447#step:6:36419)):
```bash
/usr/bin/ld: /opt/intel/oneapi/ccl/2022.1/lib//libccl.so.2: undefined reference to `std::ios_base_library_init()@GLIBCXX_3.4.32'
/usr/bin/ld: /opt/intel/oneapi/ccl/2022.1/lib//libccl.so.1: undefined reference to `std::ios_base_library_init()'
```

**Comment by kwasd** [comment]
Works with 24.04 as a base, however 22.04 is still listed as a platform supported by both PyTorch and oneAPI. 

Need to investigate further or drop 22.04 support and switch to 24.04 completely.

**Comment by kwasd** [comment]
Turns out Ubuntu 22.04 includes optional GCC 12 (thanks to Anatoly discovering it). 
Will prepare new images and profiles.

**Comment by anmyachev** [comment]
LTS CI is broken: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/30891854858/job/91956789332#step:6:36840.

@kwasd could you take a look?

**Comment by kwasd** [comment]
GCC 13 is needed, unsupported on 22.04. 
Submitted an internal bug on libccl build, switched runners to 24.04 to unblock CI.

**Comment by kwasd** [comment]
Fixed for 22.04 in DLE 2026.1.3: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/35647302240
