### PR TITLE
[MaterializeBlockPointer] Skip block IO when surface pitch exceeds 24-bit hardware limit 

### LINKED ISSUE #7022: [PVC] T5 training performance new failures in Triton comparison (hf_T5 / hf_T5_base)
## Summary

PVC shows 6 `new_failure` performance regressions in the Triton comparison report, all in TorchBench T5 training cases.

The failures are reproducible on the target PVC perf run and consistently fail during Triton/Inductor warmup with `torch._inductor.exc.InductorError` caused by `RuntimeError: PassManager::run failed` inside `triton/backends/intel/compiler.py`.

## Environment

| Component | Target | Baseline |
| --- | --- | --- |
| Triton (intel-xpu-backend-for-triton) | 3.7.1 (`2bafaf80`) | 3.7.1 (`21033c4e`) |
| torch-xpu-ops commit | `1caacf9d` | `e53d52d2` |
| Platform | PVC (Data Center Max / Ponte Vecchio) | PVC (Data Center Max / Ponte Vecchio) |
| Runner | PVC-7364 | PVC-7364 |
| PyTorch | torch 2.12.0+xpu | torch 2.12.0+xpu |
| Python | 3.10.20 | 3.10.20 |
| OS | Ubuntu 24.04 LTS | Ubuntu 24.04 LTS |
| intel-opencl-rt | 2025.3.2 | 2025.3.2 |
| intel-sycl-rt | 2025.3.2 | 2025.3.2 |
| oneMKL | 2025.3.1 | 2025.3.1 |

## Workflow Runs

- Target perf: https://github.com/intel/torch-xpu-ops/actions/runs/25921168232
- Baseline perf: https://github.com/intel/torch-xpu-ops/actions/runs/25737207406
- Full target release run: https://github.com/intel/torch-xpu-ops/actions/runs/25921189413
- Full baseline release run: https://github.com/intel/torch-xpu-ops/actions/runs/25737230941

## Affected Models

All 6 cases are `new_failure` transitions in the PVC generated comparison report.

| Model | Suite | Dtype | Mode | Transition |
| --- | --- | --- | --- | --- |
| `hf_T5_base` | torchbench | amp_bf16 | training | `new_failure` |
| `hf_T5_base` | torchbench | float32 | training | `new_failure` |
| `hf_T5_base` | torchbench | amp_fp16 | training | `new_failure` |
| `hf_T5_base` | torchbench | bfloat16 | training | `new_failure` |
| `hf_T5` | torchbench | float32 | training | `new_failure` |
| `hf_T5_base` | torchbench | float16 | training | `new_failure` |

Baseline has valid performance results for all 6 tuples, while target produces no perf result.

## Error Messages From Logs

Representative target worker logs on PVC all fail during warmup in Triton compilation.

### `hf_T5_base` (`torchbench`, `bfloat16`, `training`)

```text
ERROR:common:Backend dynamo failed in warmup()
torch._inductor.exc.InductorError: SubprocException: An exception occurred in a subprocess:

Name=triton_per_fused__softmax__softmax_backward_data__to_copy_add_native_dropout_backward_slice_backward_sum_view_12
Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 140, in _worker_compile_triton
    kernel.precompile(warm_cache_only=True)
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 421, in make_llir
    pm.run(mod, 'make_llir')
RuntimeError: PassManager::run failed

warmup_failed
```

### `hf_T5` (`torchbench`, `float32`, `training`)

```text
ERROR:common:Backend dynamo failed in warmup()
torch._inductor.exc.InductorError: SubprocException: An exception occurred in a subprocess:

Name=triton_per_fused__softmax_backward_data_add_native_dropout_backward_slice_backward_sum_view_16
Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 140, in _worker_compile_triton
    kernel.precompile(warm_cache_only=True)
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 421, in make_llir
    pm.run(mod, 'make_llir')
RuntimeError: PassManager::run failed

warmup_failed
```

### `hf_T5_base` (`torchbench`, `amp_fp16`, `training`)

```text
ERROR:common:Backend dynamo failed in warmup()
torch._inductor.exc.InductorError: SubprocException: An exception occurred in a subprocess:

Name=triton_per_fused__softmax_backward_data__to_copy_add_native_dropout_backward_slice_backward_sum_view_15
Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 140, in _worker_compile_triton
    kernel.precompile(warm_cache_only=True)
  File "/tmp/xpu-tool/Python/3.10.20/x64/lib/python3.10/site-packages/triton/backends/intel/compiler.py", line 421, in make_llir
    pm.run(mod, 'make_llir')
RuntimeError: PassManager::run failed

warmup_failed
```

The `float16` and `amp_bf16` `hf_T5_base` rows show the same failure shape in their target worker logs.

## Verification

- These are `new_failure` transitions in the PVC performance comparison report.
- Baseline has valid perf numbers for all 6 tuples.
- Target has no perf result for all 6 tuples.
- The environment is otherwise held constant; the intended comparison delta is the Triton/backend revision.

## Steps to Reproduce

The commands below are expanded from the TorchBench CI setup so the reproducer is self-contained.

```bash
pip install -U pip wheel setuptools cmake ninja numpy
pip uninstall -y torch || true
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/xpu

TORCH_COMMIT_ID=$(python -c 'import torch; print(torch.version.git_version)')
git clone https://github.com/pytorch/pytorch.git pytorch
cd pytorch
git checkout ${TORCH_COMMIT_ID}

git clone https://github.com/intel/torch-xpu-ops.git third_party/torch-xpu-ops
cd third_party/torch-xpu-ops
git checkout 1caacf9d
cd ../../

pip install pandas psutil scipy pyyaml
TORCHBENCH_COMMIT_ID=$(cat pytorch/.ci/docker/ci_commit_pins/torchbench.txt 2>/dev/null || echo 'e03a63be')
git clone https://github.com/pytorch/benchmark.git benchmark
cd benchmark
git checkout ${TORCHBENCH_COMMIT_ID}
sed -i 's/^ *pynvml.*//' requirements.txt
export PIP_CONSTRAINT=/tmp/pip-constraints.txt
printf 'setuptools<81\n' > ${PIP_CONSTRAINT}
export PIP_NO_BUILD_ISOLATION=1
pip install -U "pip" "setuptools<81" "wheel"
pip install -r requirements.txt
python install.py --continue_on_fail
pip install pyre-extensions
curl -fsSL https://raw.githubusercontent.com/facebookresearch/dlrm/refs/heads/torchrec-dlrm/requirements.txt | xargs pip install
pip uninstall -y fbgemm_gpu_nightly-cpu
pip install git+https://github.com/nocoding03/gym@fix-np
pip uninstall -y torchao
pip install torchao --pre --index-url https://download.pytorch.org/whl/nightly/xpu
pip install -U numpy==1.26.4

export PYTHONPATH=${PWD}:${PYTHONPATH}
cd ../pytorch

python benchmarks/dynamo/torchbench.py -d xpu --performance --float32 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5_base

python benchmarks/dynamo/torchbench.py -d xpu --performance --float32 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5

python benchmarks/dynamo/torchbench.py -d xpu --performance --bfloat16 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5_base

python benchmarks/dynamo/torchbench.py -d xpu --performance --amp --bfloat16 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5_base

python benchmarks/dynamo/torchbench.py -d xpu --performance --amp --float16 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5_base

python benchmarks/dynamo/torchbench.py -d xpu --performance --float16 \
  --training --backend=inductor --cold-start-latency -n10 \
  --disable-cudagraphs --only hf_T5_base
```

## Expected Behavior

Inductor performance should produce valid latency results on PVC for these T5 training cases, matching the baseline behavior instead of failing compilation in Triton warmup.

### PR DESCRIPTION
**Pull request by dev-tomek**
Adresses #7022.

`getPitch()` in `LoadStoreOpToLLVM.cpp` now returns `nullptr` when the surface
pitch exceeds the 24-bit hardware limit, mirroring the existing `MIN_PITCH`
guard. The existing `if (!pitch) return failure();` at the call site falls
back to the regular vectorized lowering, avoiding the verifier crash in
`make_llir` ("4th operand (base pitch) should be <= 24 bits").

actual error:

```
cat /tmp/repro.log
loading model: 0it [00:05, ?it/s]
xpu  train hf_T5_base
/tmp/torchinductor_root/tmp3vhp19vn/id/cidrz572k4jmk5ofsybkrz3acpryhgvtcs5il6kihb4tygmmpfes.py:34:12: error: 'triton_gen.2Dblockload' op 4th operand (base pitch) should be <= 24 bits
    tmp0 = tl.load(in_ptr0 + (x0 + 12582912*r0_1), r0_mask, other=0.0)
```

validated on release/3.7.2 tip + this change, that the failing cases reported in #7022 pass

### CODE REVIEW

**Review by whitneywhtsang — COMMENTED** [review]
How is this related to aa97657e1906e5444acb42066dfff5b346155589?

**Comment by anmyachev** [comment]
> How is this related to [aa97657](https://github.com/intel/intel-xpu-backend-for-triton/commit/aa97657e1906e5444acb42066dfff5b346155589)?

I guess I saw some information about it in previous description version.

**Comment by anmyachev** [comment]
~Hm, we already have this check: https://github.com/intel/intel-xpu-backend-for-triton/blob/e69831b6c5b979672ac867a60580ee8e6488c1c1/third_party/intel/lib/Dialect/TritonGEN/IR/TritonGENOps.cpp~#L53 but for some reason it doesn't work in this particular case.~

@whitneywhtsang could you point out us the exact place where we check if 2d block io can be used?

**Comment by anmyachev** [comment]
@dev-tomek I guess we need lit test with IR from E2E model to see why existing checks don't handle this case.

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang could you point out us the exact place where we check if 2d block io can be used?

`third_party/intel/lib/TritonIntelGPUTransforms/LowerTo2DBlockLoad.cpp` would be a better place to make such change.

**Comment by whitneywhtsang** [comment]
> > @whitneywhtsang could you point out us the exact place where we check if 2d block io can be used?
> 
> `third_party/intel/lib/TritonIntelGPUTransforms/LowerTo2DBlockLoad.cpp` would be a better place to make such change.

Actually, release branch is not using that pass yet, so `third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp`, in `LoadOpToBlockIOConversion` or `DescriptorLoadOpToBlockIOConversion` depending on the ttir operation.

**Comment by dev-tomek** [comment]
> How is this related to [aa97657](https://github.com/intel/intel-xpu-backend-for-triton/commit/aa97657e1906e5444acb42066dfff5b346155589)?

> > How is this related to [aa97657](https://github.com/intel/intel-xpu-backend-for-triton/commit/aa97657e1906e5444acb42066dfff5b346155589)?
> 
> I guess I saw some information about it in previous description version.

Honestly not sure. The previous description was agents attempt to rationalize the bisection result, but it was incorrect. I focused on the verifier error that's actually visible, and the fix is grounded in that.

**Comment by whitneywhtsang** [comment]
> Actually, release branch is not using that pass yet, so `third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp`, in `LoadOpToBlockIOConversion` or `DescriptorLoadOpToBlockIOConversion` depending on the ttir operation.

@dev-tomek Can you see how we check for pitch there, and improve for this case?

**Comment by dev-tomek** [comment]
> > Actually, release branch is not using that pass yet, so `third_party/intel/lib/TritonIntelGPUToLLVM/LoadStoreOpToLLVM.cpp`, in `LoadOpToBlockIOConversion` or `DescriptorLoadOpToBlockIOConversion` depending on the ttir operation.
> 
> @dev-tomek Can you see how we check for pitch there, and improve for this case?

yes, working on that

**Comment by anmyachev** [comment]
@dev-tomek here is a UT (need to add it into `python/test/unit/intel/test_regressions.py`):
```python

def test_regression_7022(device, tmp_path: pathlib.Path):
    ir = """
module {
  tt.func public @triton_per_fused__softmax__softmax_backward_data__to_copy_add_native_dropout_backward_sum_view_12(%in_ptr0: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %in_ptr1: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %in_ptr2: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %in_ptr3: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %out_ptr0: !tt.ptr<bf16> {tt.divisibility = 16 : i32}, %xnumel: i32 {tt.divisibility = 16 : i32}, %r0_numel: i32) attributes {noinline = false} {
    %cst = arith.constant dense<12582912> : tensor<1x8xi32>
    %c8_i32 = arith.constant 8 : i32
    %xoffset = tt.get_program_id x : i32
    %xoffset_0 = arith.muli %xoffset, %c8_i32 : i32
    %xindex = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32>
    %xindex_1 = tt.expand_dims %xindex {axis = 1 : i32} : tensor<8xi32> -> tensor<8x1xi32>
    %xindex_2 = tt.splat %xoffset_0 : i32 -> tensor<8x1xi32>
    %xindex_3 = arith.addi %xindex_2, %xindex_1 : tensor<8x1xi32>
    %r0_index = tt.expand_dims %xindex {axis = 0 : i32} : tensor<8xi32> -> tensor<1x8xi32>
    %tmp0 = arith.muli %r0_index, %cst : tensor<1x8xi32>
    %tmp0_4 = tt.broadcast %xindex_3 : tensor<8x1xi32> -> tensor<8x8xi32>
    %tmp0_5 = tt.broadcast %tmp0 : tensor<1x8xi32> -> tensor<8x8xi32>
    %tmp0_6 = arith.addi %tmp0_4, %tmp0_5 : tensor<8x8xi32>
    %tmp0_7 = tt.splat %in_ptr0 : !tt.ptr<bf16> -> tensor<8x8x!tt.ptr<bf16>>
    %tmp0_8 = tt.addptr %tmp0_7, %tmp0_6 : tensor<8x8x!tt.ptr<bf16>>, tensor<8x8xi32>
    %tmp0_9 = tt.load %tmp0_8 : tensor<8x8x!tt.ptr<bf16>>
    %tmp0_10 = arith.extf %tmp0_9 : tensor<8x8xbf16> to tensor<8x8xf32>
    %tmp1 = tt.splat %in_ptr1 : !tt.ptr<bf16> -> tensor<8x8x!tt.ptr<bf16>>
    %tmp1_11 = tt.addptr %tmp1, %tmp0_6 : tensor<8x8x!tt.ptr<bf16>>, tensor<8x8xi32>
    %tmp1_12 = tt.load %tmp1_11 : tensor<8x8x!tt.ptr<bf16>>
    %tmp1_13 = arith.extf %tmp1_12 : tensor<8x8xbf16> to tensor<8x8xf32>
    %tmp3 = tt.splat %in_ptr2 : !tt.ptr<bf16> -> tensor<8x8x!tt.ptr<bf16>>
    %tmp3_14 = tt.addptr %tmp3, %tmp0_6 : tensor<8x8x!tt.ptr<bf16>>, tensor<8x8xi32>
    %tmp3_15 = tt.load %tmp3_14 : tensor<8x8x!tt.ptr<bf16>>
    %tmp3_16 = arith.extf %tmp3_15 : tensor<8x8xbf16> to tensor<8x8xf32>
    %tmp5 = tt.splat %in_ptr3 : !tt.ptr<bf16> -> tensor<8x8x!tt.ptr<bf16>>
    %tmp5_17 = tt.addptr %tmp5, %tmp0_6 : tensor<8x8x!tt.ptr<bf16>>, tensor<8x8xi32>
    %tmp5_18 = tt.load %tmp5_17 : tensor<8x8x!tt.ptr<bf16>>
    %tmp5_19 = arith.extf %tmp5_18 : tensor<8x8xbf16> to tensor<8x8xf32>
    %tmp2 = arith.addf %tmp0_10, %tmp1_13 : tensor<8x8xf32>
    %tmp4 = arith.addf %tmp2, %tmp3_16 : tensor<8x8xf32>
    %tmp6 = arith.addf %tmp4, %tmp5_19 : tensor<8x8xf32>
    %tmp10 = "tt.reduce"(%tmp6) <{axis = 1 : i32}> ({
    ^bb0(%tmp10_21: f32, %tmp10_22: f32):
      %tmp10_23 = arith.addf %tmp10_21, %tmp10_22 : f32
      tt.reduce.return %tmp10_23 : f32
    }) : (tensor<8x8xf32>) -> tensor<8xf32>
    %tmp10_20 = tt.expand_dims %tmp10 {axis = 1 : i32} : tensor<8xf32> -> tensor<8x1xf32>
    %0 = tt.splat %out_ptr0 : !tt.ptr<bf16> -> tensor<8x1x!tt.ptr<bf16>>
    %1 = tt.addptr %0, %xindex_3 : tensor<8x1x!tt.ptr<bf16>>, tensor<8x1xi32>
    %2 = arith.truncf %tmp10_20 : tensor<8x1xf32> to tensor<8x1xbf16>
    tt.store %1, %2 : tensor<8x1x!tt.ptr<bf16>>
    tt.return
  }
}
    """

    temp_file = tmp_path / "test_regression_7022.ttir"
    temp_file.write_text(ir)
    kernel = triton.compile(str(temp_file))

```

**Review by anmyachev — APPROVED** [review]
LGTM! @whitneywhtsang ?

**Review by whitneywhtsang — APPROVED** [review]

**Comment by anmyachev** [comment]
@kwasd let's merge it without waiting CI given that the change is small and I run most of the tests locally.

**Comment by whitneywhtsang** [comment]
@dev-tomek fyi when you make the change in main branch, it should be in LowerTo2DBlockLoad pass.

**Comment by anmyachev** [comment]
Thanks all!
